kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.14
    commands:
      - cd pkg/leet
      - go test
  - name: build
    image: golang:1.14
    commands:
      - cd cmd/leet
      - export CGO_ENABLED=0
      - go build -o leet
  - name: run
    depends_on:
      - build
    image: alpine:3.11.6
    commands:
      - cd cmd/leet
      - ./leet APPLE
